/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Favorite } from "./Favorite";
import { FavoriteCountArgs } from "./FavoriteCountArgs";
import { FavoriteFindManyArgs } from "./FavoriteFindManyArgs";
import { FavoriteFindUniqueArgs } from "./FavoriteFindUniqueArgs";
import { DeleteFavoriteArgs } from "./DeleteFavoriteArgs";
import { FavoriteService } from "../favorite.service";
@graphql.Resolver(() => Favorite)
export class FavoriteResolverBase {
  constructor(protected readonly service: FavoriteService) {}

  async _favoritesMeta(
    @graphql.Args() args: FavoriteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Favorite])
  async favorites(
    @graphql.Args() args: FavoriteFindManyArgs
  ): Promise<Favorite[]> {
    return this.service.favorites(args);
  }

  @graphql.Query(() => Favorite, { nullable: true })
  async favorite(
    @graphql.Args() args: FavoriteFindUniqueArgs
  ): Promise<Favorite | null> {
    const result = await this.service.favorite(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Favorite)
  async deleteFavorite(
    @graphql.Args() args: DeleteFavoriteArgs
  ): Promise<Favorite | null> {
    try {
      return await this.service.deleteFavorite(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
